language: c

sudo: false

matrix:
  include:
    - env: LUA="lua 5.1"
      os: osx
    - env: LUA="lua 5.1"
      os: linux
    - env: LUA="lua 5.2"
      os: linux
    - env: LUA="lua 5.3"
      os: linux
    - env: LUA="lua 5.4"
      os: linux
    - env: LUA="luajit 2.0"
      os: linux
    - env: LUA="luajit 2.1"
      os: linux

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master
    - curl_mime

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip2 install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate

install:
  - luarocks make rockspecs/lua-llthreads2-compat-scm-0.rockspec
  - luarocks make rockspecs/lua-llthreads2-scm-0.rockspec

script: 
  - cd test
  - lua test_version.lua
  - lua test_table_copy.lua
  - lua test_threads.lua 10
  - lua test_llthreads.lua
  - lua test_join_timeout.lua
  - lua test_join_detach.lua
  - lua test_join_error.lua
  - lua test_register_ffi.lua
  - lua test_logger.lua
  - lua test_pass_cfunction.lua
  - lua test_load_llthreads2.lua
  - lua test_alive.lua
  - lua test_threads_ex.lua 10
  - lua test_threads_ex_arg.lua
  - lua test_threads_ex_opt.lua
  - lua test_threads_ex_opt_2.lua
  - lua test_threads_attr.lua
  - lua test_integer.lua
  - lua test_interrupt.lua
  - lua test_error.lua
  # - lua test_register_llthreads.lua

notifications:
  email:
    on_success: change
    on_failure: always
