version: 0.3.2.{build}

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LR_EXTERNAL: c:\external

  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "lua 5.4"

platform:
  - x64
  - x86
  # - mingw

cache:
  - c:\hererocks -> appveyor.yml
  - c:\external -> appveyor.yml

install:
  - echo "Setup..."
  - set PATH=C:\Python27\Scripts;%LR_EXTERNAL%;%PATH%
  - if /I "%platform%"=="x86" set HR_TARGET=vs_32
  - if /I "%platform%"=="x64" set HR_TARGET=vs_64
  - if /I "%platform%"=="mingw" set HR_TARGET=mingw
  - if /I "%platform%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if not exist "%LR_EXTERNAL%" (
      mkdir "%LR_EXTERNAL%" &&
      mkdir "%LR_EXTERNAL%\lib" &&
      mkdir "%LR_EXTERNAL%\include"
    )
  - if not exist c:\hererocks (
      pip install hererocks &&
      hererocks c:\hererocks --%LUA% --target %HR_TARGET% -rlatest
    )
  - call c:\hererocks\bin\activate

before_build:
  # external deps

build_script:
  - echo "Making..."
  - luarocks make rockspecs/lua-llthreads2-compat-scm-0.rockspec
  - luarocks make rockspecs/lua-llthreads2-scm-0.rockspec

before_test:
  # test deps

test_script:
  - echo "Testing..."
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - lua test_version.lua
  - lua test_table_copy.lua
  - lua test_threads.lua 10
  - lua test_llthreads.lua
  - lua test_join_timeout.lua
  - lua test_join_detach.lua
  - lua test_join_error.lua
  - lua test_register_ffi.lua
  - lua test_logger.lua
  - lua test_pass_cfunction.lua
  - lua test_load_llthreads2.lua
  - lua test_alive.lua
  - lua test_threads_ex.lua 10
  - lua test_threads_ex_arg.lua
  - lua test_threads_ex_opt.lua
  - lua test_threads_ex_opt_2.lua
  - lua test_threads_attr.lua
  - lua test_integer.lua
  - lua test_interrupt.lua
  - lua test_error.lua
  # - lua test_register_llthreads.lua

after_test:
  # deploy
